using './main.bicep'
param environmentName = 'treasurer-dev'
param location = 'eastus2'
param foundryResourceGroupName = 'rg-admin-7817'
param foundryAccountName = 'admin-7817-resource'
param foundryProjectName = 'admin-7817'
param foundryProjectEndpoint = 'https://admin-7817-resource.services.ai.azure.com/api/projects/admin-7817'
param foundryAgentName = 'caStateTreasurerOffice-chatbot'
